# Generated by Django 5.2.7 on 2025-10-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaznaniy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
