# Generated by Django 5.2.6 on 2025-10-28 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaznaniy', '0002_userprogress_total_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок совета')),
                ('content', models.TextField(help_text='Основной текст совета с форматированием', verbose_name='Содержание совета')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='bazaznaniy.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Полезный совет',
                'verbose_name_plural': 'Полезные советы',
                'ordering': ['topic', 'order', 'title'],
                'indexes': [models.Index(fields=['topic', 'is_active', 'order'], name='bazaznaniy__topic_i_3fba12_idx')],
            },
        ),
    ]
