# Generated by Django 5.2.7 on 2025-10-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaznaniy', '0002_alter_sector_slug_alter_topic_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TheTopic',
        ),
    ]
